
package Interfaz;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author LUIS
 */
public final class Diseño extends javax.swing.JFrame {
    INSERTAR insertar;
    public void ventanas(){
    insertar = new INSERTAR();
    }
    public Diseño() {
        initComponents();
        ventanas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        JPanelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanelAparicion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelBase.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBase.setLayout(null);

        JPanelMenu.setLayout(null);

        jButton1.setText("INSERTAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPanelMenu.add(jButton1);
        jButton1.setBounds(10, 110, 240, 80);

        jButton2.setText("ELIMINAR");
        JPanelMenu.add(jButton2);
        jButton2.setBounds(10, 290, 240, 80);

        jButton3.setText("MODIFICAR");
        JPanelMenu.add(jButton3);
        jButton3.setBounds(10, 198, 240, 80);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 22)); // NOI18N
        jLabel1.setText("     MENU");
        JPanelMenu.add(jLabel1);
        jLabel1.setBounds(70, 30, 120, 40);

        jButton4.setText("SALIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        JPanelMenu.add(jButton4);
        jButton4.setBounds(10, 540, 240, 80);

        jPanelBase.add(JPanelMenu);
        JPanelMenu.setBounds(0, 0, 260, 660);

        javax.swing.GroupLayout jPanelAparicionLayout = new javax.swing.GroupLayout(jPanelAparicion);
        jPanelAparicion.setLayout(jPanelAparicionLayout);
        jPanelAparicionLayout.setHorizontalGroup(
            jPanelAparicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanelAparicionLayout.setVerticalGroup(
            jPanelAparicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanelBase.add(jPanelAparicion);
        jPanelAparicion.setBounds(270, 0, 840, 660);

        getContentPane().add(jPanelBase);
        jPanelBase.setBounds(0, 0, 1110, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
          
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     nuevopanel(insertar);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diseño().setVisible(true);
            }
        });
    } 
    public void nuevopanel(JPanel panelActual){
   jPanelAparicion.removeAll();//
   jPanelAparicion.add(panelActual);
   jPanelAparicion.revalidate();
    jPanelAparicion.repaint();//
  
   }
//    public void cambiarPanel(JPanel panelAnterior, JPanel nuevoPanel) {
//    getContentPane().remove(panelAnterior);
//    getContentPane().add(nuevoPanel);
//    revalidate();
//    repaint();
//}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAparicion;
    private javax.swing.JPanel jPanelBase;
    // End of variables declaration//GEN-END:variables
}
