
package Interfaz;


import com.sun.jdi.connect.spi.Connection;
import conexionMysql.Conexion;
import conexionMysql.Estudiante;
import conexionMysql.Matricula;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import conexionMysql.conector;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LUIS
 */
public final class Diseño extends javax.swing.JFrame {
    private int fm=-1;
     private ArrayList<Estudiante> lista_estudiantes;
    private ArrayList<Matricula> lista_matricula;
    Conexion c = new Conexion("jdbc:mysql://localhost:3306", "universidad", "root", "");
  
    public Diseño() throws SQLException {
        initComponents();
        lista_estudiantes=c.obtenerEstudiantes();
        lista_matricula= c.obtenerMatriculas();
        MandardDatosTabla(c.obtenerDatosTabla(lista_estudiantes, lista_matricula));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        JPanelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanelAparicion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        prim_nombre = new javax.swing.JTextField();
        primer_apellido = new javax.swing.JTextField();
        Num_matricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fecha_nacimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        seg_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        seg_apellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelBase.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBase.setLayout(null);

        JPanelMenu.setBackground(new java.awt.Color(0, 102, 204));
        JPanelMenu.setForeground(new java.awt.Color(255, 51, 51));
        JPanelMenu.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("INSERTAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPanelMenu.add(jButton1);
        jButton1.setBounds(10, 110, 240, 80);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        JPanelMenu.add(jButton2);
        jButton2.setBounds(10, 290, 240, 80);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("MODIFICAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        JPanelMenu.add(jButton3);
        jButton3.setBounds(10, 198, 240, 80);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("    MENU");
        JPanelMenu.add(jLabel1);
        jLabel1.setBounds(70, 30, 120, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("SALIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        JPanelMenu.add(jButton4);
        jButton4.setBounds(10, 540, 240, 80);

        jPanelBase.add(JPanelMenu);
        JPanelMenu.setBounds(0, 0, 260, 660);

        jPanelAparicion.setBackground(new java.awt.Color(0, 102, 204));
        jPanelAparicion.setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("FORMULARIO ");
        jPanelAparicion.add(jLabel2);
        jLabel2.setBounds(340, 20, 150, 50);

        prim_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prim_nombreActionPerformed(evt);
            }
        });
        jPanelAparicion.add(prim_nombre);
        prim_nombre.setBounds(180, 110, 90, 28);
        jPanelAparicion.add(primer_apellido);
        primer_apellido.setBounds(310, 110, 90, 28);
        jPanelAparicion.add(Num_matricula);
        Num_matricula.setBounds(470, 180, 120, 28);

        jLabel3.setText(" Primer_Nombre");
        jPanelAparicion.add(jLabel3);
        jLabel3.setBounds(180, 90, 100, 16);

        jLabel4.setText("Primer_Apellido");
        jPanelAparicion.add(jLabel4);
        jLabel4.setBounds(310, 90, 100, 16);

        jLabel6.setText("N_matricula");
        jPanelAparicion.add(jLabel6);
        jLabel6.setBounds(480, 160, 67, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Fecha Nacimiento", "Fecha Matricula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanelAparicion.add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 720, 350);
        jPanelAparicion.add(fecha_nacimiento);
        fecha_nacimiento.setBounds(460, 110, 120, 28);

        jLabel7.setText("Fecha Nacimiento");
        jPanelAparicion.add(jLabel7);
        jLabel7.setBounds(470, 90, 100, 16);

        seg_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seg_nombreActionPerformed(evt);
            }
        });
        jPanelAparicion.add(seg_nombre);
        seg_nombre.setBounds(180, 180, 90, 28);

        jLabel5.setText("        Segundo_Nombre");
        jPanelAparicion.add(jLabel5);
        jLabel5.setBounds(140, 160, 150, 16);
        jPanelAparicion.add(seg_apellido);
        seg_apellido.setBounds(310, 180, 90, 28);

        jLabel8.setText("Segundo_Apellido");
        jPanelAparicion.add(jLabel8);
        jLabel8.setBounds(310, 160, 100, 16);

        jPanelBase.add(jPanelAparicion);
        jPanelAparicion.setBounds(270, 0, 840, 660);

        getContentPane().add(jPanelBase);
        jPanelBase.setBounds(0, 0, 1110, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
          
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(null, "GRACIAS POR USAR EL PROGRAMA MACPATO");
        System.exit(0);
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre1= prim_nombre.getText();
        String nombre2= seg_nombre.getText();
        String apellido1= primer_apellido.getText();
        String apellido2= seg_apellido.getText();
        String fechaNacimiento= fecha_nacimiento.getText();
        int idMatricula=Integer.parseInt(Num_matricula.getText());
        if (CamposVacios()) {
            JOptionPane.showMessageDialog(null, "Hay algun campo queno deberia estar vacio");
        }
        Estudiante e =new Estudiante(nombre1, nombre2, apellido1, apellido2, fechaNacimiento, idMatricula);
         try {
             if(c.InsertarEstudiante(e)){
              limpiar();
             ActualizarDatos();}
         } catch (SQLException ex) {
             Logger.getLogger(Diseño.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int a=jTable1.getSelectedRow();
         try {
             c.eliminarEstudiante(lista_estudiantes.get(a));
             ActualizarDatos();
         } catch (SQLException ex) {
             Logger.getLogger(Diseño.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void prim_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prim_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prim_nombreActionPerformed

    private void seg_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seg_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seg_nombreActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          if (fm==-1) {
           return; 
        }
        Estudiante e = lista_estudiantes.get(fm);
        
        e.setNombre1(prim_nombre.getText());
        e.setNombre2(seg_nombre.getText());
        e.setApellido1(primer_apellido.getText());
        e.setApellido2(seg_apellido.getText());
        e.setFechaNacimiento(fecha_nacimiento.getText());
        e.setIdMatricula(Integer.parseInt(Num_matricula.getText()));
        if (CamposVacios()) {
            JOptionPane.showMessageDialog(null, "Hay algun campo queno deberia estar vacio");
        }
        try {
             if(c. modificarEstudiante(e)){
              limpiar();
             ActualizarDatos();
             fm=-1;
             }
         } catch (SQLException ex) {
             Logger.getLogger(Diseño.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
        fm= jTable1.getSelectedRow();
        
        Estudiante e = lista_estudiantes.get(fm);
        if(e != null){
         prim_nombre.setText(e.getNombre1());
         seg_nombre.setText(e.getNombre2());
        primer_apellido.setText(e.getApellido1());
         seg_apellido.setText(e.getApellido2());
         fecha_nacimiento.setText(e.getFechaNacimiento());
        Num_matricula.setText(String.valueOf(e.getIdMatricula()));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Diseño i =new Diseño();
                    i.setVisible(true);
                     i.setSize(1070, 700);
                    i.setResizable(false);
                    i.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } catch (SQLException ex) {
                    Logger.getLogger(Diseño.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    } 
    
    public void limpiar(){
    prim_nombre.setText("");
    seg_nombre.setText("");
    primer_apellido.setText("");
    seg_apellido.setText("");
    fecha_nacimiento.setText("");
    Num_matricula.setText("");
    
    }
    public boolean CamposVacios(){
         return prim_nombre.getText().isEmpty()|| primer_apellido.getText().isEmpty()|| seg_apellido.getText().isEmpty()||fecha_nacimiento.getText().isEmpty()
                 ||Num_matricula.getText().isEmpty();
    }
    
     public void MandardDatosTabla(ArrayList<String[]>filas) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nombre");
    model.addColumn("Apellido");
    model.addColumn("Fecha de nacimiento");
    model.addColumn("Fecha de matrícula");
    jTable1.setModel(model);
         for (String[] fila : filas) {
             model.addRow(fila);
         }

}
     public void ActualizarDatos() throws SQLException{
    lista_estudiantes = c.obtenerEstudiantes();
    MandardDatosTabla(c.obtenerDatosTabla(lista_estudiantes, lista_matricula));

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelMenu;
    private javax.swing.JTextField Num_matricula;
    private javax.swing.JTextField fecha_nacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelAparicion;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField prim_nombre;
    private javax.swing.JTextField primer_apellido;
    private javax.swing.JTextField seg_apellido;
    private javax.swing.JTextField seg_nombre;
    // End of variables declaration//GEN-END:variables
}
