/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import conexionMysql.conector;
import conexionMysql.conector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.crypto.AEADBadTagException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LUIS
 */
public class INSERTAR extends javax.swing.JPanel {

    private static Connection conectar=null;
    PreparedStatement ps=null;
    ResultSet RS = null;
    public INSERTAR() {
        initComponents();
        obtenerDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("FORMULARIO ");
        add(jLabel1);
        jLabel1.setBounds(340, 20, 150, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(180, 110, 90, 28);
        add(jTextField3);
        jTextField3.setBounds(310, 110, 90, 28);
        add(jTextField5);
        jTextField5.setBounds(470, 180, 120, 28);

        jLabel2.setText(" Primer_Nombre");
        add(jLabel2);
        jLabel2.setBounds(180, 90, 100, 16);

        jLabel4.setText("Primer_Apellido");
        add(jLabel4);
        jLabel4.setBounds(310, 90, 100, 16);

        jLabel6.setText("N_matricula");
        add(jLabel6);
        jLabel6.setBounds(480, 160, 67, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Fecha Nacimiento", "Fecha Matricula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 720, 350);
        add(jTextField6);
        jTextField6.setBounds(460, 110, 120, 28);

        jLabel7.setText("Fecha Nacimiento");
        add(jLabel7);
        jLabel7.setBounds(470, 90, 100, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(180, 180, 90, 28);

        jLabel3.setText("        Segundo_Nombre");
        add(jLabel3);
        jLabel3.setBounds(140, 160, 150, 16);
        add(jTextField4);
        jTextField4.setBounds(310, 180, 90, 28);

        jLabel5.setText("Segundo_Apellido");
        add(jLabel5);
        jLabel5.setBounds(310, 160, 100, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
   public static void obtenerDatos() {
    conector c = new conector();
    Connection con = c.conexion();
    String sql = "SELECT CONCAT(Nombre1, ' ', Nombre2) AS Nombres, CONCAT(apellido1, ' ', apellido2) AS Apellidos, fecha_nacimiento, fecha_mat FROM estudiantes INNER JOIN matricula ON estudiantes.N_matricula = matricula.N_matricula;";
    Statement stmt;
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nombre");
    model.addColumn("Apellido");
    model.addColumn("Fecha de nacimiento");
    model.addColumn("Fecha de matrícula");
    jTable1.setModel(model);
    String[] datos = new String[4];
    try {
        stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            datos[0] = rs.getString(1);
            datos[1] = rs.getString(2);
            datos[2] = rs.getDate(3).toString();
            datos[3] = rs.getDate(4).toString();
            model.addRow(datos);
        }
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
